# .github/workflows/coverage.yml
name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - run: pip install nox==2022.11.21
    - run: pip install poetry==1.2.0
    - run: nox --sessions tests-3.11 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
